config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.8
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/bsc-wdc/dislib:
      branch: master
      repo: https://github.com/bsc-wdc/dislib
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/bsc-wdc/dislib git:
        commands:
        - /usr/bin/env sh .sqa/script.sloppy-viridian-guppy.sh
        container: qc.acc_flabby-bistre-wasp
  QC.Doc:
    repos:
      github.com/bsc-wdc/dislib find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.nerdy-flax-alligator.sh
        container: qc.doc_boozy-thistle-eleuth
      github.com/bsc-wdc/dislib git:
        commands:
        - /usr/bin/env sh .sqa/script.freaky-pumpkin-mandrill.sh
        container: qc.doc_surly-corn-bombay
      github.com/bsc-wdc/dislib markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.messy-bistre-bat.sh
        container: qc.doc_cozy-amethyst-indri
      github.com/bsc-wdc/dislib restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.shabby-linen-lobster.sh
        container: qc.doc_beady-peach-deer
  QC.Lic:
    repos:
      github.com/bsc-wdc/dislib licensee:
        commands:
        - /usr/bin/env sh .sqa/script.breezy-white-markhor.sh
        container: qc.lic_skinny-fuchsia-guppy
  QC.Sec:
    repos:
      github.com/bsc-wdc/dislib bandit:
        commands:
        - /usr/bin/env sh .sqa/script.gamy-mustard-cockroach.sh
        container: qc.sec_cranky-pumpkin-quoll
  QC.Sty:
    repos:
      github.com/bsc-wdc/dislib flake8:
        commands:
        - /usr/bin/env sh .sqa/script.crappy-coral-urchin.sh
        container: qc.sty_flabby-grey-lobster
      github.com/bsc-wdc/dislib hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-smalt-dragonfly.sh
        container: qc.sty_sleepy-firebrick-fowl
  QC.Ver:
    repos:
      github.com/bsc-wdc/dislib get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.clammy-ecru-gopher.sh
        container: qc.ver_woozy-ecru-schnauzer
timeout: 5400
