config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.8
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/eosc-synergy/dislib:
      branch: master
      repo: https://github.com/eosc-synergy/dislib
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/eosc-synergy/dislib git:
        commands:
        - /usr/bin/env sh .sqa/script.pasty-harlequin-mole.sh
        container: qc.acc_wimpy-chestnut-shrimp
  QC.Doc:
    repos:
      github.com/eosc-synergy/dislib find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.pasty-green-zonkey.sh
        container: qc.doc_woozy-olivine-wolfhound
      github.com/eosc-synergy/dislib git:
        commands:
        - /usr/bin/env sh .sqa/script.sunny-brass-oyster.sh
        container: qc.doc_snoopy-chartreuse-mongoose
      github.com/eosc-synergy/dislib markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-dandelion-dog.sh
        container: qc.doc_whiny-cerise-raccoon
      github.com/eosc-synergy/dislib restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.shaky-cerise-wolfhound.sh
        container: qc.doc_shabby-coral-bonobo
  QC.Lic:
    repos:
      github.com/eosc-synergy/dislib licensee:
        commands:
        - /usr/bin/env sh .sqa/script.baggy-lavender-mist.sh
        container: qc.lic_squeaky-myrtle-booby
  QC.Sec:
    repos:
      github.com/eosc-synergy/dislib bandit:
        commands:
        - /usr/bin/env sh .sqa/script.surly-blue-beagle.sh
        container: qc.sec_freaky-purple-ostrich
  QC.Sty:
    repos:
      github.com/eosc-synergy/dislib flake8:
        commands:
        - /usr/bin/env sh .sqa/script.sickly-lavender-forest.sh
        container: qc.sty_pasty-crimson-mandrill
      github.com/eosc-synergy/dislib hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.hazy-wheat-worm.sh
        container: qc.sty_scanty-chocolate-bat
  QC.Ver:
    repos:
      github.com/eosc-synergy/dislib get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.queasy-cinnabar-sloth.sh
        container: qc.ver_whiny-lime-goose
timeout: 5400
