config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.8
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/eosc-synergy/dislib:
      branch: master
      repo: https://github.com/eosc-synergy/dislib
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/eosc-synergy/dislib git:
        commands:
        - /usr/bin/env sh .sqa/script.surly-indigo-warthog.sh
        container: qc.acc_jumpy-zucchini-goose
  QC.Doc:
    repos:
      github.com/eosc-synergy/dislib find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.bumpy-cornflower-mongoose.sh
        container: qc.doc_pretty-plum-russel
      github.com/eosc-synergy/dislib git:
        commands:
        - /usr/bin/env sh .sqa/script.muggy-corn-mammoth.sh
        container: qc.doc_shaky-chestnut-woodpecker
      github.com/eosc-synergy/dislib markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.whiny-magenta-grouse.sh
        container: qc.doc_wimpy-teal-ostrich
      github.com/eosc-synergy/dislib restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.cranky-plum-goat.sh
        container: qc.doc_randy-ecru-liger
  QC.Lic:
    repos:
      github.com/eosc-synergy/dislib licensee:
        commands:
        - /usr/bin/env sh .sqa/script.freaky-violet-molly.sh
        container: qc.lic_squirrely-white-leopard
  QC.Sec:
    repos:
      github.com/eosc-synergy/dislib bandit:
        commands:
        - /usr/bin/env sh .sqa/script.scaly-ultramarine-dollar.sh
        container: qc.sec_sunny-champagne-dog
  QC.Sty:
    repos:
      github.com/eosc-synergy/dislib flake8:
        commands:
        - /usr/bin/env sh .sqa/script.snappy-carmine-ant.sh
        container: qc.sty_trippy-tan-capybara
      github.com/eosc-synergy/dislib hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.seedy-ochre-centipede.sh
        container: qc.sty_clammy-violet-tortoise
  QC.Ver:
    repos:
      github.com/eosc-synergy/dislib get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.scaly-ruby-hedgehog.sh
        container: qc.ver_gummy-heliotrope-fish
timeout: 5400
