config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.8
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/eosc-synergy/dislib:
      branch: master
      repo: https://github.com/eosc-synergy/dislib
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/eosc-synergy/dislib git:
        commands:
        - /usr/bin/env sh .sqa/script.lovely-auburn-spoonbill.sh
        container: qc.acc_lovely-wheat-lynx
  QC.Doc:
    repos:
      github.com/eosc-synergy/dislib find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.squeaky-beige-owl.sh
        container: qc.doc_blurry-ecru-serval
      github.com/eosc-synergy/dislib git:
        commands:
        - /usr/bin/env sh .sqa/script.frumpy-sangria-manatee.sh
        container: qc.doc_skinny-rose-liger
      github.com/eosc-synergy/dislib markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.skimpy-lavender-maltese.sh
        container: qc.doc_geeky-ultramarine-vulture
      github.com/eosc-synergy/dislib restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.lanky-mauve-flounder.sh
        container: qc.doc_slaphappy-amaranth-birman
  QC.Lic:
    repos:
      github.com/eosc-synergy/dislib licensee:
        commands:
        - /usr/bin/env sh .sqa/script.lumpy-ochre-mandrill.sh
        container: qc.lic_lumpy-zucchini-havanese
  QC.Sec:
    repos:
      github.com/eosc-synergy/dislib bandit:
        commands:
        - /usr/bin/env sh .sqa/script.thirsty-charcoal-gharial.sh
        container: qc.sec_breezy-blue-dolphin
  QC.Sty:
    repos:
      github.com/eosc-synergy/dislib flake8:
        commands:
        - /usr/bin/env sh .sqa/script.droopy-violet-numbat.sh
        container: qc.sty_skimpy-viridian-burmese
      github.com/eosc-synergy/dislib hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.shabby-scarlet-hornet.sh
        container: qc.sty_craggy-thistle-bear
  QC.Ver:
    repos:
      github.com/eosc-synergy/dislib get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.foggy-turquoise-armadillo.sh
        container: qc.ver_squeaky-turquoise-robin
timeout: 5400
