config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.8
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/eosc-synergy/dislib:
      branch: master
      repo: https://github.com/eosc-synergy/dislib
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/eosc-synergy/dislib git:
        commands:
        - /usr/bin/env sh .sqa/script.wheezy-indigo-bulldog.sh
        container: qc.acc_cranky-chocolate-nightingale
  QC.Doc:
    repos:
      github.com/eosc-synergy/dislib find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.tasty-ivory-llama.sh
        container: qc.doc_shabby-lavender-gopher
      github.com/eosc-synergy/dislib git:
        commands:
        - /usr/bin/env sh .sqa/script.ready-lime-tiger.sh
        container: qc.doc_cozy-grey-corgi
      github.com/eosc-synergy/dislib markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.craggy-apricot-ladybird.sh
        container: qc.doc_lovely-dandelion-avocet
      github.com/eosc-synergy/dislib restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.goopy-platinum-shark.sh
        container: qc.doc_snippy-firebrick-mayfly
  QC.Lic:
    repos:
      github.com/eosc-synergy/dislib licensee:
        commands:
        - /usr/bin/env sh .sqa/script.snippy-fuchsia-worm.sh
        container: qc.lic_flabby-cream-wolf
  QC.Sec:
    repos:
      github.com/eosc-synergy/dislib bandit:
        commands:
        - /usr/bin/env sh .sqa/script.zippy-corn-kudu.sh
        container: qc.sec_pasty-emerald-salamander
  QC.Sty:
    repos:
      github.com/eosc-synergy/dislib flake8:
        commands:
        - /usr/bin/env sh .sqa/script.woolly-mauve-loon.sh
        container: qc.sty_lovely-purple-walrus
      github.com/eosc-synergy/dislib hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.bluesy-tangerine-akbash.sh
        container: qc.sty_silly-magnolia-warthog
  QC.Ver:
    repos:
      github.com/eosc-synergy/dislib get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.lumpy-seashell-insect.sh
        container: qc.ver_slimy-copper-macaque
timeout: 5400
