config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.8
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/eosc-synergy/dislib:
      branch: master
      repo: https://github.com/eosc-synergy/dislib
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/eosc-synergy/dislib git:
        commands:
        - /usr/bin/env sh .sqa/script.breezy-pear-cattle.sh
        container: qc.acc_greasy-platinum-leopard
  QC.Doc:
    repos:
      github.com/eosc-synergy/dislib find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.skanky-cream-grasshopper.sh
        container: qc.doc_surly-blue-budgerigar
      github.com/eosc-synergy/dislib git:
        commands:
        - /usr/bin/env sh .sqa/script.fuzzy-white-quokka.sh
        container: qc.doc_slimy-crimson-echidna
      github.com/eosc-synergy/dislib markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.muggy-blue-squid.sh
        container: qc.doc_flimsy-pumpkin-dogfish
      github.com/eosc-synergy/dislib restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.randy-xanthic-shrew.sh
        container: qc.doc_sunny-ochre-zorse
  QC.Lic:
    repos:
      github.com/eosc-synergy/dislib licensee:
        commands:
        - /usr/bin/env sh .sqa/script.skinny-silver-lion.sh
        container: qc.lic_chewy-bistre-cat
  QC.Sec:
    repos:
      github.com/eosc-synergy/dislib bandit:
        commands:
        - /usr/bin/env sh .sqa/script.breezy-beige-vulture.sh
        container: qc.sec_crappy-pumpkin-mammoth
  QC.Sty:
    repos:
      github.com/eosc-synergy/dislib flake8:
        commands:
        - /usr/bin/env sh .sqa/script.goopy-orchid-monkey.sh
        container: qc.sty_slimy-cobalt-angelfish
      github.com/eosc-synergy/dislib hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.trippy-ochre-raccoon.sh
        container: qc.sty_flabby-grey-dunker
  QC.Ver:
    repos:
      github.com/eosc-synergy/dislib get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.leaky-malachite-dalmatian.sh
        container: qc.ver_woolly-peach-fowl
timeout: 5400
